[package]
name = "thalos_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
thalos_core = { path = "../thalos-core" }
thalos_models = { path = "../thalos-models" }
thalos-planning = { path = "../thalos-planning" }
thalos-collision = { path = "../thalos-collision" }
thiserror = "2"
chrono = "0.4"
rand = "0.8"
tokio = { version = "1", features = ["sync", "rt", "macros", "net", "io-util"] }
async-trait = "0.1"
arc-swap = "1"
