[workspace]
resolver = "2"

members = [
    "crates/thalos-api",
    "crates/thalos-core",
    "crates/thalos-math",
    "crates/thalos-models",
    "crates/thalos-collision",
    "crates/thalos-visual",
    "crates/thalos-runtime", 
    "crates/thalos-planning",
    "crates/thalos-optimization",
    "crates/thalos-document",
    "crates/thalos-compiler",
    "crates/thalos-semantic"
    ]
