pub mod motion_recorder;
pub mod motion_trace;
pub mod plan;
pub mod robot_command;
pub mod session;
pub mod state;
pub mod services;
pub mod telemetry;
pub mod commands;
pub mod backends;
pub mod snapshots;
pub mod error;

pub use commands::dispatch::Command;
pub use error::{ControllerError, RuntimeError};
pub use backends::controller::{BackendCapabilities, RobotController};
pub use backends::execution::ExecutionBackend;
pub use motion_trace::{MotionSample, MotionTrace};
pub use robot_command::RobotCommand;
pub use plan::{ActiveMotionPlan, ExecutionSession, MotionType, PlanState, SessionStatus};
pub use session::{ExecutionSource, SessionData, SessionManager, SessionWithTrace};
pub use telemetry::{ExecutionEvent, ExecutionSample, ExecutionTrace, TraceMetadata};
pub use services::scene::SceneService;
pub use services::singularity::SingularityService;
pub use services::workspace::WorkspaceService;
pub use services::manipulability::ManipulabilityService;
pub use services::plan_analysis::{PlanAnalysisResult, PlanAnalysisService};
pub use snapshots::scene::RuntimeSnapshot;
pub use snapshots::scene::TickDelta;
pub use state::robot_state::{RobotState, MotionState, JointState, CartesianState, DeviceState, ExecutionState, Diagnostics, MotionMode, ConnectionState, RobotError};
